"""Remove salt colunm from users table

Revision ID: 3fa1202d1105
Revises: cb17dacf23ef
Create Date: 2025-07-06 00:13:29.150075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3fa1202d1105'
down_revision = 'cb17dacf23ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', mysql.VARCHAR(length=32), nullable=True))

    # ### end Alembic commands ###
